### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by dugaldmorrow** [karma-runner/karma-intellij#25]
I'm in a team that use the Intellij karma plugin to run unit tests. We use a shared karma.conf.js which others in my team are able to use to run and debug unit tests. However, I am unable to debug and run unit tests. When I attempt to debug unit tests, I see two tabs ("Test Run" and "Karma Server"), but I am missing two tabs that my colleagues see ("Debugger" and "Scripts").

It looks my setup is misconfigured- has anyone got any clues?

![image](https://cloud.githubusercontent.com/assets/7801272/3183657/69f764a0-ec72-11e3-9300-d96182297a61.png)

**Comment by segrey** [comment]
https://youtrack.jetbrains.com/issue/WEB-8925 is fixed. Closing this.
