### ISSUE TITLE
Add support for karma-cljs-test

### ISSUE THREAD

**Issue by danielcompton** [karma-runner/karma-intellij#27]
I'm using [karma-cljs-test](https://github.com/honzabrecka/karma-cljs-test) to run ClojureScript tests in IntelliJ. Things are working pretty well, but scroll to source doesn't seem to be working. I'm guessing that tests need to report some extra metadata for IntelliJ to use. I'm happy to help add support, but can someone point me in the right direction of what metadata needs to be reported?

**Comment by segrey** [comment]
Hi Daniel,
...sorry for the long reply. What plugin are you using for ClojureScript in IntelliJ? I suspect that it doesn't implement JSFile under the hood, thus scroll to source doesn't work. There is an idea to employ source maps for languages not implementing `com.intellij.lang.javascript.psi.JSFile` (e.g. kotlin). Please follow https://youtrack.jetbrains.com/issue/WEB-16695

**Comment by danielcompton** [comment]
Hi @segrey, I'm using Cursive for my Clojure and ClojureScript editing.
