### ISSUE TITLE
Karma-intellij with karma-webpack does not wait for webpack to recompile 

### ISSUE THREAD

**Issue by c-abramson** [karma-runner/karma-intellij#35]
Hello,

I'm using karma-intellij with karma-webpack (https://github.com/webpack-contrib/karma-webpack) to point to a webpack configuration file in my karma.webpack.conf.js. One option karma-webpack provides is to use webpackBlocker, which is specified as a beforeMiddleware in the karma configuration:

```
 beforeMiddleware: [
   'webpackBlocker'
 ],
```

This middleware should block Karma from executing tests if code is recompiling, but it doesn't seem to produce the desired effect in karma-intellij. I can't reproduce this issue outside of Intellij (debugging through a browser or watching the Karma server output in a console).

Without this option, it's possible to make a code change, run the tests, and be unaware that they are actually executing against an outdated compilation.

I noticed setting the refresh flag to true in the POST request to Karma seems to solve the issue, regardless of if webpackBlocker is being used or not - (see https://github.com/karma-runner/karma-intellij/blob/master/lib/intellijRunner.js#L75) but I'm not sure that's the appropriate solution.

**Comment by devoto13** [comment]
~I've made a minimal reproduction of this issue here: https://github.com/devoto13/karma-issue-81~ It's not reliable. See comment in the linked issue.

**Comment by segrey** [comment]
@c-abramson Thanks for reporting. Even though passing `refresh: true` will slow down a test run a bit, it's worth doing. Fix will be available in WebStorm 2017.2.1.

**Comment by c-abramson** [comment]
Thanks for looking into this. I'm less convinced than I was originally that setting refresh: true fixes this issue reliably.

Would the fix make its way into IntelliJ as well?

Thanks.

**Comment by segrey** [comment]
Yes, Karma plugin with the fix will uploaded for IntelliJ as well.
